# Generated by Django 4.0 on 2022-07-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
